apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: power-engine
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/lanrewadge/kubernetes-power-engine:dev
  - target:
      kind: ConfigMap
      name: power-engine-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: development
